#!/usr/bin/python

import sys
import os
import BaseHTTPServer, SimpleHTTPServer
import ssl
import subprocess
import shlex
import socket

OPENSSL_CONF_TEMPLATE="/opt/simplehttpsserver/openssl.cnf.template"

DESCRIPTION="""Usage: {0} <ip> <port>

In summary, This script will generate a HTTPS Server indexing the current directory for serving page requests.

It utilizes openssl to generate self-signed ssl keys and then launch the SSL server utilizing the key. The directory in which the python file is present is indexed by the server for serving requests. Note that 2 new files are created by the server: 
    * SSL Certificate: for the HTTPS Server, self-signed
    * OpenSSL conf file: to generate self-signed cert with IP in SAN
It will also attempt to clean up the generate ssl keys, when interrupted with CTRL + C.

Arguments:
    ip=IP to put on the SSL cert Subject Name
    port=SSL port on which to run the ssl server

Requirements:
    * /usr/bin/openssl (OpenSSL Linux Binary)
    
    * Correct file path to opensslconf template should be specified in 
      OPENSSL_CONF_TEMPLATE constant. If installed through the following
      command, then the default OPENSSL_CONF_TEMPLATE value is correct.
        git clone https://github.com/manasmbellani/simplehttpsserver /opt/simplehttpsserver/
    
    * Executing directory must be writable to generate and cleanup 
      server.pem and openssl conf file generated

Examples:
    * To start HTTPS Server on port 443 on the localhost in current dir, simple move {0} to the appropriate server directory and run, 
        {0} 127.0.0.1 443
        
      On client side, execute following to download test.txt from the server dir:
         wget --no-check-certificate https://127.0.0.1/test.txt
                OR 
         curl -k https://127.0.0.1/test.txt

Credits:
    * jww, for providing info on stackoverflow on how to generate conf 
      file for modifying conf file to generate SSL self-signed SAN cert.
      This cert ensure that the hostname matches existing IP, reducing
      one warning generated by http request tools like wget, curl. 
      Original post is here:
        https://stackoverflow.com/questions/21488845/how-can-i-generate-a-self-signed-certificate-with-subjectaltname-using-openssl

    * dergachev, for the core on how to wrap SimpleHTTPServer in HTTPS.
      Original script available here:
        https://gist.github.com/dergachev/7028596""".format(sys.argv[0])

if len(sys.argv) < 3:
    print DESCRIPTION
    sys.exit(1)

ip = sys.argv[1]

try:
    port = int(sys.argv[2])
    if port <= 0:
        raise ValueError("Invalid value provided")
except Exception as e:
    print "[-] Error generated: {0}".format(str(e))
    sys.exit(2)

try:
    if not os.path.exists(OPENSSL_CONF_TEMPLATE):
        raise ValueError("Openssl conf file does not exist")

    print "[*] Reading existing conf file"
    with open(OPENSSL_CONF_TEMPLATE, "rb+") as f:
        conf_file_tmpl = f.read()
    conf_file_tmpl_with_ip = conf_file_tmpl + "\n\n[ alternate_names ]\n"
    conf_file_tmpl_with_ip += "IP.1 = {0}\n".format(ip)
    
    print "[*] Creating new conf file"
    with open("conf_file.config", "wb+") as f:
        f.write(conf_file_tmpl_with_ip)
        
except Exception as e:
    print "[-] Error when read openssl cnf file template: {0}".format(str(e))
    sys.exit(3)

print "[*] Generating the SSL key and cert via openssl"
p = subprocess.Popen(shlex.split("/usr/bin/openssl req -config conf_file.config -new -x509 -keyout server.pem -out server.pem -days 365 -nodes -subj \"/C=US/ST=Denial/L=Springfield/O=Dis/CN={0}\"".format(ip)), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(out, err) = p.communicate()
print "Output: {0}".format(out)
print "Error : {0}".format(err)

try:
    print "[*] Launching the HTTPS Server on  ({0},{1})".format(ip, port)
    httpd = BaseHTTPServer.HTTPServer((ip, port), SimpleHTTPServer.SimpleHTTPRequestHandler)
    httpd.socket = ssl.wrap_socket (httpd.socket, certfile='./server.pem', server_side=True)
    httpd.serve_forever()
except socket.error as e:
    print "[-] socket.error: {0}".format(str(e))
except KeyboardInterrupt as e:
    print "[-] Cleaning up SSL cert"
    os.remove("server.pem")

    print "[-] Cleaning up config file"
    os.remove("conf_file.config")
